apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-1
  namespace: gw-lab
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 9443
    hostname: shop-gw.local