apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-1
  namespace: gw-lab
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 9080
    hostname: shop-gw.local
    allowedRoutes:
      namespaces:
        from: Same
  - name: https
    protocol: HTTPS
    port: 9444
    hostname: shop-gw.local
    tls:
      certificateRefs:
      - kind: Secret
        name: tls-secret
    allowedRoutes:
      namespaces:
        from: Same