apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          securityContext:
            readOnlyRootFilesystem: true