apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
    containers:
      - name: web
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true