apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: kustomize-lab
    component: api
spec:
  selector:
    app: kustomize-lab
    component: api
  ports:
    - name: http
      port: 80
      targetPort: http
