apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: kustomize-lab
    component: web
spec:
  selector:
    app: kustomize-lab
    component: web
  ports:
    - name: http
      port: 80
      targetPort: http
