apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                name: api-secret
                key: token